### ISSUE TITLE
The shut down button does not work with PM2

### ISSUE THREAD

**Issue by Kazzer78** [EbenKouao/MMM-SmartTouch#5]
Hi,

First of all great module you need to do more!!!

I cant get the shut down button to work with PM2. If i stop PM2 (pm2 stop 0) then start magic mirror by "npm start" it works.
Is there anyway of fixing this? (All the rest of the buttons work fine with pm2 it's just the shut down button)

Thanks

**Comment by Kazzer78** [comment]
Hi, 

Is anyone looking in to this?

Thanks

**Comment by nicolgit** [comment]
+1 shutdown button just do not work for me both using PM2 or npm start.

here the log I see on ssh


```
[24.01.2021 10:46.51.399] [LOG]   Error: Command failed: shutdown -h now
Failed to set wall message, ignoring: Interactive authentication required.
Failed to power off system via logind: Interactive authentication required.
Failed to open initctl fifo: Permission denied
Failed to talk to init daemon.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:658:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'shutdown -h now'
}  Failed to set wall message, ignoring: Interactive authentication required.
Failed to power off system via logind: Interactive authentication required.
Failed to open initctl fifo: Permission denied
Failed to talk to init daemon.
```
